pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'
variables:
  buildConfiguration: 'Release'
  Build.ArtifactStagingDirectory: './release'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.300'
    displayName: 'DotnetCoreInstall'
  - script: dotnet restore
  - script: dotnet build
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True
    /p:DesktopBuildPackageLocation="../package.zip"